name: Lint

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Get changed files
        id: changed-files
        uses: Ana06/get-changed-files@v2.1.0
        with:
          format: space-delimited
          filter: |
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ESLint
        run: bun lint:report ${{ steps.changed-files.outputs.added_modified }}
