name: Test Config

on:
  pull_request:
    paths:
      - 'apps/web/src/config/**'
      - 'packages/pools/src/**'
      - 'packages/farms/constants/**'
      - 'packages/tokens/src/**'
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node: [18]

    name: Config (Jest)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Run tests
        run: bun test:config
